climate.basement:
  name:
  platform: nest
  unique_id: hQnJexEvBzuTYj09BP8NS4vlwJFn_0Xc
climate.upstairs:
  name:
  platform: nest
  unique_id: hQnJexEvBzv_1QxlvZz4aIvlwJFn_0Xc
media_player.tv:
  name:
  platform: cast
  unique_id: 26f78a5d-cc0c-d14b-8efc-383753d7af30
sensor.allergy_index_historical_average:
  name:
  platform: pollen
  unique_id: 78717_allergy_index_historical_average
sensor.allergy_index_today:
  name:
  platform: pollen
  unique_id: 78717_allergy_index_today
sensor.allergy_index_tomorrow:
  name:
  platform: pollen
  unique_id: 78717_allergy_index_tomorrow
sensor.allergy_index_yesterday:
  name:
  platform: pollen
  unique_id: 78717_allergy_index_yesterday
sensor.cold__flu_forecasted_average:
  name:
  platform: pollen
  unique_id: 78717_cold__flu_forecasted_average
sensor.allergy_index_forecasted_average:
  name:
  platform: pollen
  unique_id: 78717_allergy_index_forecasted_average
media_player.bravia_4k_gb:
  name:
  platform: plex
  unique_id: fb51bda869fcde59-com-plexapp-android
switch.switch:
  name: front_porch
  platform: zwave
  unique_id: 2-72057594076282880
